--------------------------------------------------------
--  File created - Friday-December-13-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table HCL_SK_ITEM
--------------------------------------------------------

  CREATE TABLE "HCL_DBUSER"."HCL_SK_ITEM" 
   (	"ID" NUMBER(*,0), 
	"NAME" VARCHAR2(30 CHAR), 
	"PRICE" NUMBER(*,0), 
	"MANUFACTURER_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TEST" ;
REM INSERTING into HCL_DBUSER.HCL_SK_ITEM
SET DEFINE OFF;
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (1,'Coolpix',5400,1);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (2,'HTC Dream',5500,2);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (3,'HTC Magic',5600,2);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (4,'HTC Hero',5700,2);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (5,'Huawei P10',5800,3);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (6,'Huawei P20',5900,3);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (7,'LG G2',6000,4);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (8,'LG G3',6100,4);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (9,'LG G4',6200,4);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (10,'LG G5',6300,4);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (11,'LG G6',6400,4);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (12,'LG G7 ThinQ',6500,4);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (13,'LG G8 ThinQ',6600,4);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (14,'LG Optimus G',6700,4);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (15,'LG V10',6800,4);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (16,'LG V20',6900,4);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (17,'LG V30',7000,4);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (18,'LG V35 ThinQ',7100,4);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (19,'LG V40 ThinQ',7200,4);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (20,'Moto C',7300,5);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (21,'Moto E3',7400,5);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (22,'Moto E4',7500,5);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (23,'Moto E5',7600,5);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (24,'Moto E 1 gen',7700,5);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (25,'Moto E (2nd gen)',7800,5);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (26,'Moto G4',7900,5);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (27,'Moto G5',8000,5);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (28,'Moto G6',8100,5);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (29,'Moto G7',8200,5);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (30,'Moto G (1st gen)',8300,5);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (31,'Moto G (2nd gen)',8400,5);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (32,'Moto G (3rd gen)',8500,5);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (33,'Motorola Photon Q',8600,5);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (34,'Moto X4',8700,5);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (35,'Moto X (1st gen)',8800,5);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (36,'Moto X (2nd gen)',8900,5);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (37,'Moto X Play',9000,5);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (38,'Moto X Style',9100,5);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (39,'Moto Z',9200,5);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (40,'Moto Z Play',9300,5);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (41,'Moto Z2 Force',9400,5);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (42,'Moto Z2 Play',9500,5);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (43,'Moto Z3 Force',9600,5);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (44,'Moto Z3 Play',9700,5);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (45,'Nextbit Robin',9800,4);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (46,'Nexus One',9900,4);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (47,'Nexus S',10000,4);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (48,'Galaxy Nexus',10100,4);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (49,'Nexus 4',10200,4);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (50,'Nexus 5',10300,4);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (51,'Nexus 6',10400,4);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (52,'Nexus 5X',10500,4);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (53,'Nexus 6P',10600,4);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (54,'Nokia X',10700,6);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (55,'Nokia X2',10800,6);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (56,'Nokia 1',10900,6);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (57,'Nokia 1 Plus',11000,6);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (58,'Nokia 2',11100,6);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (59,'Nokia 2.1',11200,6);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (60,'Nokia 2.2',11300,6);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (61,'Nokia 3',11400,6);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (62,'Nokia 3.1',11500,6);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (63,'Nokia 3.1 Plus',11600,6);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (64,'Nokia 3.2',11700,6);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (65,'Nokia 4.2',11800,6);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (66,'Nokia 5',11900,6);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (67,'Nokia 5.1',12000,6);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (68,'Nokia 5.1 Plus',12100,6);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (69,'Nokia 6',12200,6);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (70,'Nokia 6.1',12300,6);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (71,'Nokia 6.1 Plus',12400,6);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (72,'Nokia 7',12500,6);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (73,'Nokia 7 Plus',12600,6);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (74,'Nokia 7.1',12700,6);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (75,'Nokia 8',12800,6);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (76,'Nokia 8 Sirocco',12900,6);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (77,'Nokia 8.1',13000,6);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (78,'Nokia 9 PureView',13100,6);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (79,'OnePlus One',13200,7);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (80,'OnePlus 2',13300,7);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (81,'OnePlus X',13400,7);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (82,'OnePlus 3',13500,7);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (83,'OnePlus 3T',13600,7);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (84,'OnePlus 5',13700,7);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (85,'OnePlus 5T',13800,7);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (86,'OnePlus 6',13900,7);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (87,'OnePlus 6T',14000,7);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (88,'OnePlus 7',14100,7);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (89,'OnePlus 7 Pro',14200,7);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (90,'Panasonic P100',14300,8);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (91,'Samsung Galaxy',14400,9);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (92,'Samsung Galaxy S',14500,9);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (93,'Samsung Galaxy S2',14600,9);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (94,'Samsung Galaxy S3',14700,9);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (95,'Samsung Galaxy S4',14800,9);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (96,'Samsung Galaxy S4 Zoom',14900,9);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (97,'Samsung Galaxy S5',15000,9);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (98,'Samsung Galaxy S6/Edge',15100,9);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (99,'Samsung Galaxy S6 Edge+',15200,9);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (100,'Samsung Galaxy Grand Prime',15300,9);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (101,'Samsung Galaxy S7/Edge',15400,9);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (102,'Samsung Galaxy S8/+',15500,9);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (103,'Samsung Galaxy S9/+',15600,9);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (104,'Samsung Galaxy S10/e/+',15700,9);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (105,'Samsung Galaxy S10 5G',15800,9);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (106,'Samsung Galaxy Note',15900,9);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (107,'Samsung Galaxy Note 2',16000,9);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (108,'Samsung Galaxy Note 3',16100,9);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (109,'Samsung Galaxy Note 3 Neo',16200,9);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (110,'Samsung Galaxy Note 4/Edge',16300,9);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (111,'Samsung Galaxy Note 5',16400,9);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (112,'Samsung Galaxy Note 7',16500,9);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (113,'Samsung Galaxy Note FE',16600,9);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (114,'Samsung Galaxy Note 8',16700,9);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (115,'Samsung Galaxy Note 9',16800,9);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (116,'Sony Ericsson Xperia Play',16900,10);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (117,'Sony Ericsson Xperia pro',17000,10);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (118,'Sony Ericsson Xperia X10',17100,10);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (119,'Sony Ericsson Xperia X8',17200,10);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (120,'Sony Xperia XZ1',17300,10);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (121,'Sony Xperia Z',17400,10);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (122,'Sony Xperia Z1',17500,10);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (123,'Xiaomi Mi 1',17600,11);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (124,'Xiaomi Mi 2',17700,11);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (125,'Xiaomi Mi 2S/A',17800,11);
Insert into HCL_DBUSER.HCL_SK_ITEM (ID,NAME,PRICE,MANUFACTURER_ID) values (126,'Xiaomi Mi MIX Alpha',17900,11);
--------------------------------------------------------
--  DDL for Index ITEM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HCL_DBUSER"."ITEM_PK" ON "HCL_DBUSER"."HCL_SK_ITEM" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TEST" ;
--------------------------------------------------------
--  Constraints for Table HCL_SK_ITEM
--------------------------------------------------------

  ALTER TABLE "HCL_DBUSER"."HCL_SK_ITEM" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "HCL_DBUSER"."HCL_SK_ITEM" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "HCL_DBUSER"."HCL_SK_ITEM" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "HCL_DBUSER"."HCL_SK_ITEM" MODIFY ("MANUFACTURER_ID" NOT NULL ENABLE);
  ALTER TABLE "HCL_DBUSER"."HCL_SK_ITEM" ADD CONSTRAINT "ITEM_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TEST"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HCL_SK_ITEM
--------------------------------------------------------

  ALTER TABLE "HCL_DBUSER"."HCL_SK_ITEM" ADD CONSTRAINT "MANUFACTURER_FK" FOREIGN KEY ("MANUFACTURER_ID")
	  REFERENCES "HCL_DBUSER"."HCL_SK_MANUFACTURER" ("ID") ENABLE;
--------------------------------------------------------
--  DDL for Trigger HCL_SK_ITEM_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HCL_DBUSER"."HCL_SK_ITEM_ID_TRG" BEFORE
    INSERT ON hcl_sk_item
    FOR EACH ROW
     WHEN ( new.id IS NULL ) BEGIN
    :new.id := hcl_sk_item_id_seq.nextval;
END;

/
ALTER TRIGGER "HCL_DBUSER"."HCL_SK_ITEM_ID_TRG" ENABLE;
