--------------------------------------------------------
--  File created - Friday-December-13-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table HCL_SK_MANUFACTURER
--------------------------------------------------------

  CREATE TABLE "HCL_DBUSER"."HCL_SK_MANUFACTURER" 
   (	"ID" NUMBER(*,0), 
	"NAME" VARCHAR2(10 CHAR), 
	"RATING" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TEST" ;

   COMMENT ON COLUMN "HCL_DBUSER"."HCL_SK_MANUFACTURER"."RATING" IS 'Rating from 0 to 5';
REM INSERTING into HCL_DBUSER.HCL_SK_MANUFACTURER
SET DEFINE OFF;
Insert into HCL_DBUSER.HCL_SK_MANUFACTURER (ID,NAME,RATING) values (1,'Nikkon',0);
Insert into HCL_DBUSER.HCL_SK_MANUFACTURER (ID,NAME,RATING) values (2,'HTC',4);
Insert into HCL_DBUSER.HCL_SK_MANUFACTURER (ID,NAME,RATING) values (3,'Huawei',0);
Insert into HCL_DBUSER.HCL_SK_MANUFACTURER (ID,NAME,RATING) values (4,'LG',2);
Insert into HCL_DBUSER.HCL_SK_MANUFACTURER (ID,NAME,RATING) values (5,'Motorola',4);
Insert into HCL_DBUSER.HCL_SK_MANUFACTURER (ID,NAME,RATING) values (6,'Nokia',3);
Insert into HCL_DBUSER.HCL_SK_MANUFACTURER (ID,NAME,RATING) values (7,'OnePlus',5);
Insert into HCL_DBUSER.HCL_SK_MANUFACTURER (ID,NAME,RATING) values (8,'Panasonic',4);
Insert into HCL_DBUSER.HCL_SK_MANUFACTURER (ID,NAME,RATING) values (9,'Samsung',3);
Insert into HCL_DBUSER.HCL_SK_MANUFACTURER (ID,NAME,RATING) values (10,'Sony',5);
Insert into HCL_DBUSER.HCL_SK_MANUFACTURER (ID,NAME,RATING) values (11,'Xiaomi',3);
--------------------------------------------------------
--  DDL for Index MANUFACTURER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HCL_DBUSER"."MANUFACTURER_PK" ON "HCL_DBUSER"."HCL_SK_MANUFACTURER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TEST" ;
--------------------------------------------------------
--  Constraints for Table HCL_SK_MANUFACTURER
--------------------------------------------------------

  ALTER TABLE "HCL_DBUSER"."HCL_SK_MANUFACTURER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "HCL_DBUSER"."HCL_SK_MANUFACTURER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "HCL_DBUSER"."HCL_SK_MANUFACTURER" ADD CONSTRAINT "MANUFACTURER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TEST"  ENABLE;
