--------------------------------------------------------
--  File created - Friday-December-13-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table HCL_SK_ORDER
--------------------------------------------------------

  CREATE TABLE "HCL_DBUSER"."HCL_SK_ORDER" 
   (	"ITEM_ID" NUMBER(*,0), 
	"ID" NUMBER(*,0), 
	"ORDER_DATE" DATE, 
	"QUANTITY" NUMBER(*,0), 
	"PAYMENT" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TEST" ;

   COMMENT ON COLUMN "HCL_DBUSER"."HCL_SK_ORDER"."PAYMENT" IS '0 - Not paid
1 - paid';
REM INSERTING into HCL_DBUSER.HCL_SK_ORDER
SET DEFINE OFF;
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (128,204,to_date('09-DEC-19','DD-MON-RR'),1,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (129,205,to_date('09-DEC-19','DD-MON-RR'),1,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,227,to_date('11-DEC-19','DD-MON-RR'),6,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,228,to_date('11-DEC-19','DD-MON-RR'),4,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,216,to_date('10-DEC-19','DD-MON-RR'),5,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,226,to_date('11-DEC-19','DD-MON-RR'),5,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,229,to_date('11-DEC-19','DD-MON-RR'),4,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (5,488,to_date('11-DEC-19','DD-MON-RR'),4,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,495,to_date('11-DEC-19','DD-MON-RR'),3,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,496,to_date('11-DEC-19','DD-MON-RR'),3,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,497,to_date('11-DEC-19','DD-MON-RR'),5,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,510,to_date('12-DEC-19','DD-MON-RR'),6,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,517,to_date('12-DEC-19','DD-MON-RR'),2,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,518,to_date('12-DEC-19','DD-MON-RR'),6,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,523,to_date('12-DEC-19','DD-MON-RR'),4,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,528,to_date('12-DEC-19','DD-MON-RR'),4,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,529,to_date('12-DEC-19','DD-MON-RR'),4,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,534,to_date('12-DEC-19','DD-MON-RR'),6,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (1,1,to_date('05-DEC-19','DD-MON-RR'),1,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (2,2,to_date('06-DEC-18','DD-MON-RR'),2,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (3,3,to_date('07-DEC-18','DD-MON-RR'),3,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,4,to_date('08-DEC-18','DD-MON-RR'),4,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (5,5,to_date('09-DEC-18','DD-MON-RR'),5,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (6,6,to_date('10-DEC-18','DD-MON-RR'),6,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (7,7,to_date('11-DEC-18','DD-MON-RR'),7,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (8,8,to_date('12-DEC-18','DD-MON-RR'),8,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (9,9,to_date('13-DEC-18','DD-MON-RR'),9,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (10,10,to_date('14-DEC-18','DD-MON-RR'),10,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (11,11,to_date('15-DEC-18','DD-MON-RR'),1,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (12,12,to_date('16-DEC-18','DD-MON-RR'),2,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (13,13,to_date('17-DEC-18','DD-MON-RR'),3,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (14,14,to_date('18-DEC-18','DD-MON-RR'),4,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (15,15,to_date('19-DEC-18','DD-MON-RR'),5,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (16,16,to_date('20-DEC-18','DD-MON-RR'),6,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (17,17,to_date('21-DEC-18','DD-MON-RR'),7,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (18,18,to_date('22-DEC-18','DD-MON-RR'),8,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (19,19,to_date('23-DEC-18','DD-MON-RR'),9,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (20,20,to_date('24-DEC-18','DD-MON-RR'),10,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (21,21,to_date('25-DEC-18','DD-MON-RR'),1,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (22,22,to_date('26-DEC-18','DD-MON-RR'),2,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (23,23,to_date('27-DEC-18','DD-MON-RR'),3,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (24,24,to_date('28-DEC-18','DD-MON-RR'),4,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (25,25,to_date('29-DEC-18','DD-MON-RR'),5,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (26,26,to_date('30-DEC-18','DD-MON-RR'),6,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (27,27,to_date('31-DEC-18','DD-MON-RR'),7,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (28,28,to_date('01-JAN-19','DD-MON-RR'),8,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (29,29,to_date('02-JAN-19','DD-MON-RR'),9,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (30,30,to_date('03-JAN-19','DD-MON-RR'),10,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (31,31,to_date('04-JAN-19','DD-MON-RR'),1,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (32,32,to_date('05-JAN-19','DD-MON-RR'),2,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (33,33,to_date('06-JAN-19','DD-MON-RR'),3,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (34,34,to_date('07-JAN-19','DD-MON-RR'),4,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (35,35,to_date('08-JAN-19','DD-MON-RR'),5,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (36,36,to_date('09-JAN-19','DD-MON-RR'),6,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (37,37,to_date('10-JAN-19','DD-MON-RR'),7,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (38,38,to_date('11-JAN-19','DD-MON-RR'),8,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (39,39,to_date('12-JAN-19','DD-MON-RR'),9,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (40,40,to_date('13-JAN-19','DD-MON-RR'),10,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (41,41,to_date('14-JAN-19','DD-MON-RR'),1,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (42,42,to_date('15-JAN-19','DD-MON-RR'),2,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (43,43,to_date('16-JAN-19','DD-MON-RR'),3,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (44,44,to_date('17-JAN-19','DD-MON-RR'),4,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (45,45,to_date('18-JAN-19','DD-MON-RR'),5,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (46,46,to_date('19-JAN-19','DD-MON-RR'),6,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (47,47,to_date('20-JAN-19','DD-MON-RR'),7,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (48,48,to_date('21-JAN-19','DD-MON-RR'),8,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (49,49,to_date('22-JAN-19','DD-MON-RR'),9,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (50,50,to_date('23-JAN-19','DD-MON-RR'),10,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (51,51,to_date('24-JAN-19','DD-MON-RR'),1,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (52,52,to_date('25-JAN-19','DD-MON-RR'),2,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (53,53,to_date('26-JAN-19','DD-MON-RR'),3,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (54,54,to_date('27-JAN-19','DD-MON-RR'),4,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (55,55,to_date('28-JAN-19','DD-MON-RR'),5,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (56,56,to_date('29-JAN-19','DD-MON-RR'),6,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (57,57,to_date('30-JAN-19','DD-MON-RR'),7,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (58,58,to_date('31-JAN-19','DD-MON-RR'),8,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (59,59,to_date('01-FEB-19','DD-MON-RR'),9,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (60,60,to_date('02-FEB-19','DD-MON-RR'),10,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (61,61,to_date('03-FEB-19','DD-MON-RR'),1,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (62,62,to_date('04-FEB-19','DD-MON-RR'),2,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (63,63,to_date('05-FEB-19','DD-MON-RR'),3,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (64,64,to_date('06-FEB-19','DD-MON-RR'),4,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (65,65,to_date('07-FEB-19','DD-MON-RR'),5,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (66,66,to_date('08-FEB-19','DD-MON-RR'),6,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (67,67,to_date('09-FEB-19','DD-MON-RR'),7,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (68,68,to_date('10-FEB-19','DD-MON-RR'),8,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (69,69,to_date('11-FEB-19','DD-MON-RR'),9,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (70,70,to_date('12-FEB-19','DD-MON-RR'),10,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (71,71,to_date('13-FEB-19','DD-MON-RR'),1,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (72,72,to_date('14-FEB-19','DD-MON-RR'),2,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (73,73,to_date('15-FEB-19','DD-MON-RR'),3,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (74,74,to_date('16-FEB-19','DD-MON-RR'),4,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (75,75,to_date('17-FEB-19','DD-MON-RR'),5,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (76,76,to_date('18-FEB-19','DD-MON-RR'),6,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (77,77,to_date('19-FEB-19','DD-MON-RR'),7,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (78,78,to_date('20-FEB-19','DD-MON-RR'),8,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (79,79,to_date('21-FEB-19','DD-MON-RR'),9,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (80,80,to_date('22-FEB-19','DD-MON-RR'),10,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (81,81,to_date('23-FEB-19','DD-MON-RR'),1,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (82,82,to_date('24-FEB-19','DD-MON-RR'),2,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (83,83,to_date('25-FEB-19','DD-MON-RR'),3,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (84,84,to_date('26-FEB-19','DD-MON-RR'),4,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (85,85,to_date('27-FEB-19','DD-MON-RR'),5,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (86,86,to_date('28-FEB-19','DD-MON-RR'),6,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (87,87,to_date('01-MAR-19','DD-MON-RR'),7,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (88,88,to_date('02-MAR-19','DD-MON-RR'),8,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (89,89,to_date('03-MAR-19','DD-MON-RR'),9,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (90,90,to_date('04-MAR-19','DD-MON-RR'),10,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (91,91,to_date('05-MAR-19','DD-MON-RR'),1,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (92,92,to_date('06-MAR-19','DD-MON-RR'),2,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (93,93,to_date('07-MAR-19','DD-MON-RR'),3,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (94,94,to_date('08-MAR-19','DD-MON-RR'),4,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (95,95,to_date('09-MAR-19','DD-MON-RR'),5,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (96,96,to_date('10-MAR-19','DD-MON-RR'),6,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (97,97,to_date('11-MAR-19','DD-MON-RR'),7,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (98,98,to_date('12-MAR-19','DD-MON-RR'),8,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (99,99,to_date('13-MAR-19','DD-MON-RR'),9,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (100,100,to_date('14-MAR-19','DD-MON-RR'),10,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (101,101,to_date('15-MAR-19','DD-MON-RR'),1,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (102,102,to_date('16-MAR-19','DD-MON-RR'),2,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (103,103,to_date('17-MAR-19','DD-MON-RR'),3,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (104,104,to_date('18-MAR-19','DD-MON-RR'),4,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (105,105,to_date('19-MAR-19','DD-MON-RR'),5,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (106,106,to_date('20-MAR-19','DD-MON-RR'),6,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (107,107,to_date('21-MAR-19','DD-MON-RR'),7,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (108,108,to_date('22-MAR-19','DD-MON-RR'),8,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (109,109,to_date('23-MAR-19','DD-MON-RR'),9,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (110,110,to_date('24-MAR-19','DD-MON-RR'),10,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (111,111,to_date('25-MAR-19','DD-MON-RR'),1,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (112,112,to_date('26-MAR-19','DD-MON-RR'),2,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (113,113,to_date('27-MAR-19','DD-MON-RR'),3,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (114,114,to_date('28-MAR-19','DD-MON-RR'),4,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (115,115,to_date('29-MAR-19','DD-MON-RR'),5,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (116,116,to_date('30-MAR-19','DD-MON-RR'),6,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (117,117,to_date('31-MAR-19','DD-MON-RR'),7,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (118,118,to_date('01-APR-19','DD-MON-RR'),8,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (119,119,to_date('02-APR-19','DD-MON-RR'),9,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (120,120,to_date('03-APR-19','DD-MON-RR'),10,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (121,121,to_date('04-APR-19','DD-MON-RR'),1,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (122,122,to_date('05-APR-19','DD-MON-RR'),2,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (123,123,to_date('06-APR-19','DD-MON-RR'),3,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (124,124,to_date('07-APR-19','DD-MON-RR'),4,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (125,125,to_date('08-APR-19','DD-MON-RR'),5,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (1,126,to_date('09-APR-19','DD-MON-RR'),6,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (2,127,to_date('10-APR-19','DD-MON-RR'),7,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (3,128,to_date('11-APR-19','DD-MON-RR'),8,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,129,to_date('12-APR-19','DD-MON-RR'),9,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (5,130,to_date('13-APR-19','DD-MON-RR'),10,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (6,131,to_date('14-APR-19','DD-MON-RR'),1,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (7,132,to_date('15-APR-19','DD-MON-RR'),2,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (8,133,to_date('16-APR-19','DD-MON-RR'),3,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (9,134,to_date('17-APR-19','DD-MON-RR'),4,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (10,135,to_date('18-APR-19','DD-MON-RR'),5,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (11,136,to_date('19-APR-19','DD-MON-RR'),6,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (12,137,to_date('20-APR-19','DD-MON-RR'),7,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (13,138,to_date('21-APR-19','DD-MON-RR'),8,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (14,139,to_date('22-APR-19','DD-MON-RR'),9,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (15,140,to_date('23-APR-19','DD-MON-RR'),10,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (16,141,to_date('24-APR-19','DD-MON-RR'),1,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (17,142,to_date('25-APR-19','DD-MON-RR'),2,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (18,143,to_date('26-APR-19','DD-MON-RR'),3,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (19,144,to_date('27-APR-19','DD-MON-RR'),4,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (20,145,to_date('28-APR-19','DD-MON-RR'),5,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (21,146,to_date('29-APR-19','DD-MON-RR'),6,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (22,147,to_date('30-APR-19','DD-MON-RR'),7,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (23,148,to_date('01-MAY-19','DD-MON-RR'),8,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (24,149,to_date('02-MAY-19','DD-MON-RR'),9,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (25,150,to_date('03-MAY-19','DD-MON-RR'),10,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (26,151,to_date('04-MAY-19','DD-MON-RR'),1,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (27,152,to_date('05-MAY-19','DD-MON-RR'),2,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (28,153,to_date('06-MAY-19','DD-MON-RR'),3,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (29,154,to_date('07-MAY-19','DD-MON-RR'),4,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (30,155,to_date('08-MAY-19','DD-MON-RR'),5,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (31,156,to_date('09-MAY-19','DD-MON-RR'),6,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (32,157,to_date('10-MAY-19','DD-MON-RR'),7,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (33,158,to_date('11-MAY-19','DD-MON-RR'),8,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (34,159,to_date('12-MAY-19','DD-MON-RR'),9,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (35,160,to_date('13-MAY-19','DD-MON-RR'),10,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (36,161,to_date('14-MAY-19','DD-MON-RR'),1,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (37,162,to_date('15-MAY-19','DD-MON-RR'),2,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (38,163,to_date('16-MAY-19','DD-MON-RR'),3,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (39,164,to_date('17-MAY-19','DD-MON-RR'),4,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (40,165,to_date('18-MAY-19','DD-MON-RR'),5,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (41,166,to_date('19-MAY-19','DD-MON-RR'),6,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (42,167,to_date('20-MAY-19','DD-MON-RR'),7,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (43,168,to_date('21-MAY-19','DD-MON-RR'),8,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (44,169,to_date('22-MAY-19','DD-MON-RR'),9,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (45,170,to_date('23-MAY-19','DD-MON-RR'),10,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (46,171,to_date('24-MAY-19','DD-MON-RR'),1,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (47,172,to_date('25-MAY-19','DD-MON-RR'),2,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (48,173,to_date('26-MAY-19','DD-MON-RR'),3,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (49,174,to_date('27-MAY-19','DD-MON-RR'),4,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (50,175,to_date('28-MAY-19','DD-MON-RR'),5,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (51,176,to_date('29-MAY-19','DD-MON-RR'),6,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (52,177,to_date('30-MAY-19','DD-MON-RR'),7,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (53,178,to_date('31-MAY-19','DD-MON-RR'),8,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (54,179,to_date('01-JUN-19','DD-MON-RR'),9,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (55,180,to_date('02-JUN-19','DD-MON-RR'),10,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (56,181,to_date('03-JUN-19','DD-MON-RR'),1,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (57,182,to_date('04-JUN-19','DD-MON-RR'),2,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (58,183,to_date('05-JUN-19','DD-MON-RR'),3,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (59,184,to_date('06-JUN-19','DD-MON-RR'),4,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (60,185,to_date('07-JUN-19','DD-MON-RR'),5,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (61,186,to_date('08-JUN-19','DD-MON-RR'),6,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (62,187,to_date('09-JUN-19','DD-MON-RR'),7,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (63,188,to_date('10-JUN-19','DD-MON-RR'),8,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (64,189,to_date('11-JUN-19','DD-MON-RR'),9,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (65,190,to_date('12-JUN-19','DD-MON-RR'),10,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (66,191,to_date('13-JUN-19','DD-MON-RR'),1,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (67,192,to_date('14-JUN-19','DD-MON-RR'),2,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (68,193,to_date('15-JUN-19','DD-MON-RR'),3,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (69,194,to_date('16-JUN-19','DD-MON-RR'),4,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (70,195,to_date('17-JUN-19','DD-MON-RR'),5,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (71,196,to_date('18-JUN-19','DD-MON-RR'),6,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (72,197,to_date('19-JUN-19','DD-MON-RR'),7,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (73,198,to_date('20-JUN-19','DD-MON-RR'),8,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (74,199,to_date('21-JUN-19','DD-MON-RR'),9,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (75,200,to_date('22-JUN-19','DD-MON-RR'),10,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (127,203,to_date('09-DEC-19','DD-MON-RR'),1,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (130,207,to_date('09-DEC-19','DD-MON-RR'),1,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (131,208,to_date('09-DEC-19','DD-MON-RR'),1,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,230,to_date('11-DEC-19','DD-MON-RR'),5,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,233,to_date('11-DEC-19','DD-MON-RR'),5,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (7,491,to_date('11-DEC-19','DD-MON-RR'),4,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,505,to_date('12-DEC-19','DD-MON-RR'),5,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,506,to_date('12-DEC-19','DD-MON-RR'),6,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (2,215,to_date('10-DEC-19','DD-MON-RR'),3,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,224,to_date('11-DEC-19','DD-MON-RR'),5,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,511,to_date('12-DEC-19','DD-MON-RR'),2,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,515,to_date('12-DEC-19','DD-MON-RR'),2,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,521,to_date('12-DEC-19','DD-MON-RR'),4,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,524,to_date('12-DEC-19','DD-MON-RR'),4,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,531,to_date('12-DEC-19','DD-MON-RR'),1,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,536,to_date('12-DEC-19','DD-MON-RR'),4,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,538,to_date('12-DEC-19','DD-MON-RR'),4,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,222,to_date('11-DEC-19','DD-MON-RR'),2,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,223,to_date('11-DEC-19','DD-MON-RR'),4,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,232,to_date('11-DEC-19','DD-MON-RR'),5,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (10,236,to_date('11-DEC-19','DD-MON-RR'),3,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (10,237,to_date('11-DEC-19','DD-MON-RR'),3,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (2,213,to_date('10-DEC-19','DD-MON-RR'),2,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (2,214,to_date('10-DEC-19','DD-MON-RR'),3,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,221,to_date('10-DEC-19','DD-MON-RR'),9,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (16,244,to_date('11-DEC-19','DD-MON-RR'),3,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (16,245,to_date('11-DEC-19','DD-MON-RR'),3,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (16,246,to_date('11-DEC-19','DD-MON-RR'),3,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (16,247,to_date('11-DEC-19','DD-MON-RR'),3,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,493,to_date('11-DEC-19','DD-MON-RR'),3,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,500,to_date('11-DEC-19','DD-MON-RR'),6,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,502,to_date('11-DEC-19','DD-MON-RR'),6,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,504,to_date('12-DEC-19','DD-MON-RR'),6,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,509,to_date('12-DEC-19','DD-MON-RR'),6,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,514,to_date('12-DEC-19','DD-MON-RR'),6,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,516,to_date('12-DEC-19','DD-MON-RR'),6,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,519,to_date('12-DEC-19','DD-MON-RR'),4,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,525,to_date('12-DEC-19','DD-MON-RR'),5,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,530,to_date('12-DEC-19','DD-MON-RR'),4,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,537,to_date('12-DEC-19','DD-MON-RR'),4,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,225,to_date('11-DEC-19','DD-MON-RR'),6,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,231,to_date('11-DEC-19','DD-MON-RR'),3,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (10,238,to_date('11-DEC-19','DD-MON-RR'),3,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (10,239,to_date('11-DEC-19','DD-MON-RR'),3,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (10,240,to_date('11-DEC-19','DD-MON-RR'),3,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (10,241,to_date('11-DEC-19','DD-MON-RR'),3,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (6,489,to_date('11-DEC-19','DD-MON-RR'),5,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,492,to_date('11-DEC-19','DD-MON-RR'),2,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,503,to_date('12-DEC-19','DD-MON-RR'),6,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,507,to_date('12-DEC-19','DD-MON-RR'),2,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,217,to_date('10-DEC-19','DD-MON-RR'),4,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,219,to_date('10-DEC-19','DD-MON-RR'),6,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,220,to_date('10-DEC-19','DD-MON-RR'),6,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,512,to_date('12-DEC-19','DD-MON-RR'),6,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,520,to_date('12-DEC-19','DD-MON-RR'),1,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,526,to_date('12-DEC-19','DD-MON-RR'),4,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,532,to_date('12-DEC-19','DD-MON-RR'),1,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,535,to_date('12-DEC-19','DD-MON-RR'),4,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,218,to_date('10-DEC-19','DD-MON-RR'),4,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (9,234,to_date('11-DEC-19','DD-MON-RR'),3,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (10,235,to_date('11-DEC-19','DD-MON-RR'),3,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (10,242,to_date('11-DEC-19','DD-MON-RR'),3,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (10,243,to_date('11-DEC-19','DD-MON-RR'),3,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (3,490,to_date('11-DEC-19','DD-MON-RR'),4,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,494,to_date('11-DEC-19','DD-MON-RR'),4,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,498,to_date('11-DEC-19','DD-MON-RR'),6,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,499,to_date('11-DEC-19','DD-MON-RR'),6,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,501,to_date('11-DEC-19','DD-MON-RR'),6,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,508,to_date('12-DEC-19','DD-MON-RR'),6,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,513,to_date('12-DEC-19','DD-MON-RR'),1,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,522,to_date('12-DEC-19','DD-MON-RR'),1,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,527,to_date('12-DEC-19','DD-MON-RR'),4,'0');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,533,to_date('12-DEC-19','DD-MON-RR'),6,'1');
Insert into HCL_DBUSER.HCL_SK_ORDER (ITEM_ID,ID,ORDER_DATE,QUANTITY,PAYMENT) values (4,539,to_date('12-DEC-19','DD-MON-RR'),4,'1');
--------------------------------------------------------
--  DDL for Index ORDER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HCL_DBUSER"."ORDER_PK" ON "HCL_DBUSER"."HCL_SK_ORDER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TEST" ;
--------------------------------------------------------
--  Constraints for Table HCL_SK_ORDER
--------------------------------------------------------

  ALTER TABLE "HCL_DBUSER"."HCL_SK_ORDER" MODIFY ("ITEM_ID" NOT NULL ENABLE);
  ALTER TABLE "HCL_DBUSER"."HCL_SK_ORDER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "HCL_DBUSER"."HCL_SK_ORDER" ADD CONSTRAINT "ORDER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TEST"  ENABLE;
--------------------------------------------------------
--  DDL for Trigger HCL_SK_ORDER_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HCL_DBUSER"."HCL_SK_ORDER_ID_TRG" BEFORE
    INSERT ON hcl_sk_order
    FOR EACH ROW
     WHEN ( new.id IS NULL ) BEGIN
    :new.id := hcl_sk_order_id_seq.nextval;
END;

/
ALTER TRIGGER "HCL_DBUSER"."HCL_SK_ORDER_ID_TRG" ENABLE;
