--------------------------------------------------------
--  File created - Friday-December-13-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table HCL_SK_SHIPPING_ORDER
--------------------------------------------------------

  CREATE TABLE "HCL_DBUSER"."HCL_SK_SHIPPING_ORDER" 
   (	"ID" NUMBER(*,0), 
	"ORDER_ID" NUMBER(*,0), 
	"DELIVERED_DATE" DATE, 
	"SHIPPING_STATUS" CHAR(1 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TEST" ;

   COMMENT ON COLUMN "HCL_DBUSER"."HCL_SK_SHIPPING_ORDER"."DELIVERED_DATE" IS 'Updated on the day of delivery';
   COMMENT ON COLUMN "HCL_DBUSER"."HCL_SK_SHIPPING_ORDER"."SHIPPING_STATUS" IS 'S - shipped from warehouse
T - Transit
D - Delivered
U - Undelivered due to unforseen events
R - product returned without customer receiving';
REM INSERTING into HCL_DBUSER.HCL_SK_SHIPPING_ORDER
SET DEFINE OFF;
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (206,495,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (207,496,to_date('11-DEC-19','DD-MON-RR'),'d');
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (217,2,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (3,3,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (4,4,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (5,5,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (6,6,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (8,8,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (9,9,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (10,10,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (12,12,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (13,13,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (14,14,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (15,15,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (17,17,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (18,18,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (19,19,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (21,21,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (22,22,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (23,23,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (24,24,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (26,26,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (27,27,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (28,28,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (30,30,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (31,31,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (32,32,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (33,33,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (35,35,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (36,36,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (37,37,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (39,39,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (40,40,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (41,41,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (42,42,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (44,44,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (45,45,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (46,46,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (48,48,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (49,49,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (50,50,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (51,51,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (53,53,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (54,54,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (55,55,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (57,57,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (58,58,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (59,59,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (60,60,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (62,62,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (63,63,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (64,64,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (66,66,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (67,67,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (68,68,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (69,69,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (71,71,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (72,72,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (73,73,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (75,75,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (76,76,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (77,77,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (78,78,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (80,80,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (81,81,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (82,82,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (84,84,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (85,85,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (86,86,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (87,87,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (89,89,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (90,90,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (91,91,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (93,93,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (94,94,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (95,95,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (96,96,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (98,98,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (99,99,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (100,100,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (102,102,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (103,103,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (104,104,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (105,105,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (107,107,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (108,108,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (109,109,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (111,111,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (112,112,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (113,113,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (114,114,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (116,116,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (117,117,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (118,118,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (120,120,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (121,121,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (122,122,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (123,123,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (125,125,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (126,1,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (127,2,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (129,4,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (130,5,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (131,6,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (132,7,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (134,9,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (135,10,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (136,11,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (138,13,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (139,14,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (140,15,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (141,16,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (143,18,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (144,19,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (145,20,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (147,22,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (148,23,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (149,24,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (150,25,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (152,27,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (153,28,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (154,29,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (156,31,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (157,32,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (158,33,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (159,34,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (161,36,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (162,37,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (163,38,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (165,40,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (166,41,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (167,42,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (168,43,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (170,45,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (171,46,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (172,47,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (174,49,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (175,50,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (176,51,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (177,52,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (179,54,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (180,55,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (181,56,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (183,58,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (184,59,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (185,60,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (186,61,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (188,63,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (189,64,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (190,65,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (192,67,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (193,68,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (194,69,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (195,70,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (197,72,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (198,73,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (199,74,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (201,230,to_date('11-DEC-19','DD-MON-RR'),'d');
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (205,233,to_date('11-DEC-19','DD-MON-RR'),'d');
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (211,539,to_date('13-DEC-19','DD-MON-RR'),'d');
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (212,539,to_date('13-DEC-19','DD-MON-RR'),'d');
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (213,539,to_date('13-DEC-19','DD-MON-RR'),'d');
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (218,9,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (202,222,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (204,232,to_date('11-DEC-19','DD-MON-RR'),'d');
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (214,539,to_date('13-DEC-19','DD-MON-RR'),'d');
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (220,227,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (203,231,to_date('11-DEC-19','DD-MON-RR'),'d');
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (219,227,null,null);
Insert into HCL_DBUSER.HCL_SK_SHIPPING_ORDER (ID,ORDER_ID,DELIVERED_DATE,SHIPPING_STATUS) values (210,539,to_date('13-DEC-19','DD-MON-RR'),'d');
--------------------------------------------------------
--  DDL for Index SHIPPING_ORDER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HCL_DBUSER"."SHIPPING_ORDER_PK" ON "HCL_DBUSER"."HCL_SK_SHIPPING_ORDER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TEST" ;
--------------------------------------------------------
--  Constraints for Table HCL_SK_SHIPPING_ORDER
--------------------------------------------------------

  ALTER TABLE "HCL_DBUSER"."HCL_SK_SHIPPING_ORDER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "HCL_DBUSER"."HCL_SK_SHIPPING_ORDER" MODIFY ("ORDER_ID" NOT NULL ENABLE);
  ALTER TABLE "HCL_DBUSER"."HCL_SK_SHIPPING_ORDER" ADD CONSTRAINT "SHIPPING_ORDER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TEST"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HCL_SK_SHIPPING_ORDER
--------------------------------------------------------

  ALTER TABLE "HCL_DBUSER"."HCL_SK_SHIPPING_ORDER" ADD CONSTRAINT "ORDER_FK" FOREIGN KEY ("ORDER_ID")
	  REFERENCES "HCL_DBUSER"."HCL_SK_ORDER" ("ID") ENABLE;
--------------------------------------------------------
--  DDL for Trigger HCL_SK_SHIPPING_ORDER_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HCL_DBUSER"."HCL_SK_SHIPPING_ORDER_ID_TRG" BEFORE
    INSERT ON hcl_sk_shipping_order
    FOR EACH ROW
     WHEN ( new.id IS NULL ) BEGIN
    :new.id := hcl_sk_shipping_order_id_seq.nextval;
END;

/
ALTER TRIGGER "HCL_DBUSER"."HCL_SK_SHIPPING_ORDER_ID_TRG" ENABLE;
